[package]
name = "paranormle"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
wasm-logger = "0.2.0"
yew = { version = "0.21.0", features = ["csr"] }