[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.39"
lazy_static = "1.5.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
chrono-tz = "0.8"